spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:sqlserver://192.168.1.103:1433;databaseName=PRACTICE
    username: PRACTICE
    password: 
mybatis:
  configuration:
    map-underscore-to-camel-case: true
